[package]
name = "rustyduk-nucleus"
version = "0.1.0"
authors = [
  "Jeremiah Senkpiel <fishrock123@rocketmail.com",
  "Tim Caswell <tim@creationix.com>"]
build = "build.rs"

[dependencies]
getopts = "0.2"
libc = "0.2"
zip = "0.1"

[build-dependencies]
gcc = "0.3"

[[bin]]
name = "nucleus"
