[package]
name = "nucleus-chakra"
version = "0.0.0"
authors = [
  "Jeremiah Senkpiel <fishrock123@rocketmail.com",
  ]
build = "build.rs"

[dependencies]
getopts = "0.2"
libc = "0.2"
zip = "0.1"

[build-dependencies]
gcc = "0.3"

[[bin]]
name = "nucleus"
